# NOTE(boumenot): building with VS2017 and LLVM-vs2014 on AppVeyor
# does not work.  Once it does
#
# 1. drop support for VS2015
# 2. unnecessary msbuild PATH manipulation; msbuild15 is default on VS2017
# 3. add support for msbuild15's binary log (e.g. /bl:debug.binlog)

image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

skip_commits:
  files:
    - build.cmd
    - clean.cmd
    - init.cmd
    - README.md

before_build:
  # - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  - call "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x64
  - cmake --version
  - clang-cl -v
  - cl
  - msbuild /version
  - set

build_script:
  # - cmake -G "Visual Studio 15 2017 Win64" -T LLVM-vs2014 .
  - cmake -G "Visual Studio 14 2015 Win64" -T LLVM-vs2014 .
  - msbuild wapiti.sln /t:Build /p:Configuration=Debug   /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild wapiti.sln /t:Build /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - 7z a wapiti-msvc-x64-debug.7z -mx9 COPYING README.md Debug/*
  - 7z a wapiti-msvc-x64.7z       -mx9 COPYING README.md Release/*
  - appveyor PushArtifact wapiti-msvc-x64.7z wapiti-msvc-x64-debug.7z

artifacts:
  - path: wapiti-msvc-x64.7z wapiti-msvc-x64-debug.7z

# on_failure:
#   - appveyor PushArtifact debug.binlog release.binlog

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: XUHs7rAfk3ymN4Rn1ORzRZlZynQDMj3T2CxzaKusU/Zw6SYLBS8wSxt5y12+onZX
  artifact: wapiti-msvc-x64-debug.7z wapiti-msvc-x64.7z
  draft: false
  prerelease: false
  on:
    branch: master
    appveyor_repo_tag: true
